"""
PCA analysis of hidden states from connectome RNN checkpoint runs.

Loads .npy files containing hidden states (shape: T x N) and performs
PCA to visualize the neural trajectories in reduced dimensions.
The .npy files are generated by run_connectome_rnn_checkpoint.py with
save_hidden_states=True.
"""

import os
import glob
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# ---- Configuration ----
NPY_DIR = r"D:\Benquan\OneDrive MSState\OneDrive - Mississippi State University\Publications\IROS2026\materials\PCA\efficientnet_robust"

# Display labels for each file (basename without extension)
LABEL_MAP = {
    "full_vision": "Full Vision",
    "right_eye_only": "Right Eye Only",
    "total_blind": "Total Blind",
}

# Colors for each condition
COLOR_MAP = {
    "full_vision": "#2196F3",       # blue
    "right_eye_only": "#FF9800",    # orange
    "total_blind": "#F44336",       # red
}


def load_hidden_states(npy_dir: str) -> dict:
    """Load all top-level .npy and .npz files from *npy_dir*.

    For .npy files the array is used directly (expected shape T x N).
    For .npz files every array inside is flattened to 2-D (T, features)
    and then concatenated along axis=1 to produce a single (T, N) matrix.

    Returns
    -------
    data : dict[str, np.ndarray]
        Mapping from stem name (e.g. 'full_vision') to array of shape (T, N).
    """
    npy_files = sorted(glob.glob(os.path.join(npy_dir, "*.npy")))
    npz_files = sorted(glob.glob(os.path.join(npy_dir, "*.npz")))
    all_files = npy_files + npz_files
    if not all_files:
        raise FileNotFoundError(f"No .npy/.npz files found in {npy_dir}")

    data = {}
    for fpath in all_files:
        stem = os.path.splitext(os.path.basename(fpath))[0]
        if fpath.endswith(".npz"):
            npz = np.load(fpath)
            parts = []
            for key in sorted(npz.files):
                a = npz[key]                       # (T, ...) arbitrary shape
                T = a.shape[0]
                parts.append(a.reshape(T, -1))     # flatten to (T, features)
            arr = np.concatenate(parts, axis=1)     # (T, N)
            print(f"[io] Loaded {stem} (.npz, {len(npz.files)} arrays): "
                  f"shape={arr.shape}, dtype={arr.dtype}")
        else:
            arr = np.load(fpath)
            print(f"[io] Loaded {stem}: shape={arr.shape}, dtype={arr.dtype}")
        data[stem] = arr
    return data


def analyze_hidden_states(npy_dir: str = NPY_DIR) -> None:
    """Perform PCA on hidden-state trajectories and plot the results.

    Each .npy file is expected to have shape (T, N) where T is timesteps
    and N is the number of neurons.  A joint PCA is fitted on the
    concatenated data so that all conditions share the same principal axes.
    """
    # 1. Load data
    data = load_hidden_states(npy_dir)

    # 2. Concatenate all hidden states for joint PCA fitting
    all_states = np.concatenate(list(data.values()), axis=0)  # (sum_T, N)
    print(f"[pca] Joint data matrix: {all_states.shape}")

    pca = PCA(n_components=3)
    pca.fit(all_states)
    print(f"[pca] Explained variance ratio (PC1-3): {pca.explained_variance_ratio_}")

    # 3. Transform each condition separately
    projected = {}
    for stem, arr in data.items():
        projected[stem] = pca.transform(arr)  # (T, 3)

    # ---- Plot 1: 2-D PCA trajectories (PC1 vs PC2) ----
    fig, ax = plt.subplots(figsize=(8, 6))
    for stem, proj in projected.items():
        label = LABEL_MAP.get(stem, stem)
        color = COLOR_MAP.get(stem, None)
        ax.plot(proj[:, 0], proj[:, 1], linewidth=1.2, alpha=0.85,
                label=label, color=color)
        # Mark start and end
        ax.scatter(proj[0, 0], proj[0, 1], marker='o', s=60, color=color,
                   edgecolors='k', zorder=5)
        ax.scatter(proj[-1, 0], proj[-1, 1], marker='X', s=80, color=color,
                   edgecolors='k', zorder=5)

    ax.set_xlabel(f"PC1 ({pca.explained_variance_ratio_[0]*100:.1f}%)")
    ax.set_ylabel(f"PC2 ({pca.explained_variance_ratio_[1]*100:.1f}%)")
    ax.set_title("PCA of Connectome RNN Hidden States")
    ax.legend(loc="best")
    ax.grid(True, alpha=0.3)
    fig.tight_layout()

    # ---- Plot 2: PC components over time ----
    fig2, axes = plt.subplots(3, 1, figsize=(10, 7), sharex=True)
    for pc_idx, ax2 in enumerate(axes):
        for stem, proj in projected.items():
            label = LABEL_MAP.get(stem, stem)
            color = COLOR_MAP.get(stem, None)
            ax2.plot(proj[:, pc_idx], linewidth=1.0, alpha=0.85,
                     label=label, color=color)
        ax2.set_ylabel(f"PC{pc_idx+1}")
        ax2.grid(True, alpha=0.3)
        if pc_idx == 0:
            ax2.legend(loc="best", fontsize=8)
    axes[-1].set_xlabel("Time Step")
    axes[0].set_title("Principal Components Over Time")
    fig2.tight_layout()

    # ---- Plot 3: 3-D PCA trajectories ----
    fig3 = plt.figure(figsize=(9, 7))
    ax3 = fig3.add_subplot(111, projection='3d')
    for stem, proj in projected.items():
        label = LABEL_MAP.get(stem, stem)
        color = COLOR_MAP.get(stem, None)
        ax3.plot(proj[:, 0], proj[:, 1], proj[:, 2], linewidth=1.0,
                 alpha=0.8, label=label, color=color)
        ax3.scatter(proj[0, 0], proj[0, 1], proj[0, 2], marker='o', s=60,
                    color=color, edgecolors='k', zorder=5)
        ax3.scatter(proj[-1, 0], proj[-1, 1], proj[-1, 2], marker='X', s=80,
                    color=color, edgecolors='k', zorder=5)

    ax3.set_xlabel(f"PC1 ({pca.explained_variance_ratio_[0]*100:.1f}%)")
    ax3.set_ylabel(f"PC2 ({pca.explained_variance_ratio_[1]*100:.1f}%)")
    ax3.set_zlabel(f"PC3 ({pca.explained_variance_ratio_[2]*100:.1f}%)")
    ax3.set_title("3-D PCA of Connectome RNN Hidden States")
    ax3.legend(loc="best")
    fig3.tight_layout()

    plt.show()


if __name__ == "__main__":
    analyze_hidden_states()